name: Deploy React App

on:
  push:
    branches:
      - DEV

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 28101
          script: |
            cd /opt/JagaKota-FE
            git pull origin DEV

            echo "Writing .env file"
            cat <<EOF > .env
            ${{ secrets.ENV_FILE_CONTENT }}
            EOF

            docker build --no-cache \
              -t jagakota-fe . \
              --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}

            docker stop jagakota-fe_container || true
            docker rm jagakota-fe_container || true

            docker run -d \
              --name jagakota-fe_container \
              -p 4000:80 \
              jagakota-fe
